// This file is auto-generated by Supabase CLI.
// Run: pnpm supabase gen types typescript --linked > lib/supabase/types.ts
// Do not edit manually.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Database = {
  public: {
    Tables: {
      user_profiles: {
        Row: {
          id: string
          jira_account_id: string
          jira_display_name: string | null
          default_jira_project_key: string | null
          default_jira_project_name: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          jira_account_id: string
          jira_display_name?: string | null
          default_jira_project_key?: string | null
          default_jira_project_name?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          jira_account_id?: string
          jira_display_name?: string | null
          default_jira_project_key?: string | null
          default_jira_project_name?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      jira_tokens: {
        Row: {
          id: string
          encrypted_access_token: string
          encrypted_refresh_token: string | null
          token_expires_at: string
          scopes: string[]
          jira_cloud_id: string
          jira_base_url: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          encrypted_access_token: string
          encrypted_refresh_token?: string | null
          token_expires_at: string
          scopes?: string[]
          jira_cloud_id: string
          jira_base_url: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          encrypted_access_token?: string
          encrypted_refresh_token?: string | null
          token_expires_at?: string
          scopes?: string[]
          jira_cloud_id?: string
          jira_base_url?: string
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      generation_sessions: {
        Row: {
          id: string
          user_id: string
          session_type: 'requirements' | 'sprint' | 'meeting' | 'ac_enrichment'
          status: 'generating' | 'ready' | 'error' | 'in_review' | 'approved' | 'pushed'
          source_input_text: string | null
          source_input_audio_path: string | null
          source_input_transcription: string | null
          input_language: string | null
          jira_project_key: string | null
          jira_epic_id: string | null
          jira_sprint_id: string | null
          n8n_execution_id: string | null
          error_message: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          session_type: 'requirements' | 'sprint' | 'meeting' | 'ac_enrichment'
          status?: 'generating' | 'ready' | 'error' | 'in_review' | 'approved' | 'pushed'
          source_input_text?: string | null
          source_input_audio_path?: string | null
          source_input_transcription?: string | null
          input_language?: string | null
          jira_project_key?: string | null
          jira_epic_id?: string | null
          jira_sprint_id?: string | null
          n8n_execution_id?: string | null
          error_message?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          session_type?: 'requirements' | 'sprint' | 'meeting' | 'ac_enrichment'
          status?: 'generating' | 'ready' | 'error' | 'in_review' | 'approved' | 'pushed'
          source_input_text?: string | null
          source_input_audio_path?: string | null
          source_input_transcription?: string | null
          input_language?: string | null
          jira_project_key?: string | null
          jira_epic_id?: string | null
          jira_sprint_id?: string | null
          n8n_execution_id?: string | null
          error_message?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      generated_stories: {
        Row: {
          id: string
          session_id: string
          user_id: string
          title: string
          user_story_statement: string
          acceptance_criteria: Json
          priority: string | null
          labels: string[]
          story_points: number | null
          blocked_by_issue_keys: string[]
          blocks_issue_keys: string[]
          generated_title: string
          generated_user_story_statement: string
          generated_acceptance_criteria: Json
          status: 'pending' | 'approved' | 'rejected'
          jira_issue_key: string | null
          jira_issue_url: string | null
          sort_order: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          session_id: string
          user_id: string
          title: string
          user_story_statement: string
          acceptance_criteria?: Json
          priority?: string | null
          labels?: string[]
          story_points?: number | null
          blocked_by_issue_keys?: string[]
          blocks_issue_keys?: string[]
          generated_title: string
          generated_user_story_statement: string
          generated_acceptance_criteria?: Json
          status?: 'pending' | 'approved' | 'rejected'
          jira_issue_key?: string | null
          jira_issue_url?: string | null
          sort_order?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          session_id?: string
          user_id?: string
          title?: string
          user_story_statement?: string
          acceptance_criteria?: Json
          priority?: string | null
          labels?: string[]
          story_points?: number | null
          blocked_by_issue_keys?: string[]
          blocks_issue_keys?: string[]
          generated_title?: string
          generated_user_story_statement?: string
          generated_acceptance_criteria?: Json
          status?: 'pending' | 'approved' | 'rejected'
          jira_issue_key?: string | null
          jira_issue_url?: string | null
          sort_order?: number
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
    }
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: {
      session_type_enum: 'requirements' | 'sprint' | 'meeting' | 'ac_enrichment'
      session_status_enum: 'generating' | 'ready' | 'error' | 'in_review' | 'approved' | 'pushed'
      story_status_enum: 'pending' | 'approved' | 'rejected'
    }
    CompositeTypes: Record<string, never>
  }
}

export type Tables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Row']

export type Enums<T extends keyof Database['public']['Enums']> = Database['public']['Enums'][T]
